- hosts: cluster_manager
  roles:
    - role: elastic.elasticsearch
  vars:
    es_config:
      cluster.name: "test-cluster"
      discovery.seed_hosts: "192.168.122.85:9300, 192.168.122.76:9300, 192.168.122.109:9300, 192.168.122.72:9300, 192.168.122.134:9300"
      http.port: 9200
      transport.port: 9300
      node.roles: "master"
      bootstrap.memory_lock: true
      cluster.initial_master_nodes: "192.168.122.85:9300, 192.168.122.76:9300, 192.168.122.109:9300"
      network.host: 0.0.0.0
    es_heap_size: 8g
    es_enable_auto_ssl_configuration: false
    es_enable_http_ssl: false
    es_enable_transport_ssl: false
    es_ssl_upload: false

- hosts: cluster_data
  roles:
    - role: elastic.elasticsearch
  vars:
    es_config:
      cluster.name: "test-cluster"
      discovery.seed_hosts: "192.168.122.85:9300, 192.168.122.76:9300, 192.168.122.109:9300, 192.168.122.72:9300, 192.168.122.134:9300"
      http.port: 9200
      transport.port: 9300
      node.roles: "data,ingest"
      bootstrap.memory_lock: true
      cluster.initial_master_nodes: "192.168.122.85:9300, 192.168.122.76:9300, 192.168.122.109:9300"
      network.host: 0.0.0.0
    es_heap_size: 8g
    es_enable_auto_ssl_configuration: false
    es_enable_http_ssl: false
    es_enable_transport_ssl: false
    es_ssl_upload: false
